name: Shell

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
         logLevel:
           description: 'Log level'
           required: true
           default: 'warning'
           type: choice
           options:
           - info
           - warning
           - debug
         tags:
           description: 'Test scenario tags'
           required: false
           type: boolean
         environment:
           description: 'Environment to run tests against'
           type: environment
           required: true

env:
  DAY_OF_WEEK: Monday

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Before cache
        run: |
          echo before
          cat /proc/cpuinfo | grep processor

      - name: Cache
        id: cache-something
        uses: actions/cache@v3
        with:
          path: was-build.txt
          key: build-${{ hashFiles('requirements.txt', 'other.txt') }}

      - name: Building database
        run: ./build.sh


