name: Shell

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Before cache
        run: |
          echo before

      - name: Cache
        id: cache-something
        uses: actions/cache@v3
        with:
          path: was-build.txt
          key: build-${{ hashFiles('requirements.txt other.txt') }}

      - name: Building database
        run: ./build.sh


